version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install coverage
            pip install .
    
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            coverage run --source=./fluidml -m pytest --junitxml=test-reports/results.xml unittests
            coverage report
            coverage html --directory=test-reports

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
  

